### ISSUE TITLE
Flashing content in login page

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/symon#234]
**Describe the bug**
When the login page is opened, there is a flashing content of "create new user".

**To Reproduce**
1. Go to login page

**Expected behavior**
No flashing content

**Additional context**

https://user-images.githubusercontent.com/311343/122019726-61060280-cdc4-11eb-8b97-4577d5fe3bcc.mov

**Comment by ilmiawan** [comment]
@nicnocquee 
This is happened because there is a latency for checking if symon has user data or not.

```
<div className="mb-6 font-bold">
   {hasUser ? "Login" : "Create new user"}
</div>
```

Current implementation is joining the page to create new user and login. Should we start developing a separate page for creating new user and login? since currently we cannot add another user if it already has a user.

**Comment by nicnocquee** [comment]
it's easier to just show a loading indicator while it's checking for the user, isn't it?
